## **Lab Exercise #1**
- Name: Michael Kenny
- Date Started: 9/10/2025
- Date Completed: 9/10/2025
- Class: CSC-180-02
- Professor: Dr. Mamoun Abu-Samaha

**Assignment Objective:**
- Recreate the model as shown in the lecture slides for the csv file (homeprices.csv).

**Test Cases/Predictions:**
- Test1 -> area = 5000

### **1. Reading CSV File into Dataframe**

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("./homeprices.csv")
df.head()

,area,price
0,2600,550000
1,3000,565000
2,3200,610000
3,3600,680000
4,4000,725000


Creates a new variable for the read_csv function to hold out data.
We will manipulate this variable to get the information we need.

### **2. Training/Fitting Model**

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


Creating the linear model based off of the inputs: area, and outputs: price.

In my model output it shows different values for parameters than the ones in the lecture. Specifically n_jobs is None when in the lecture it shows 1. I am unsure of what this means, but all of my exercises so far have not matched with the lecture's n_jobs parameter value.

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

Model coefficient and intercept describe the equation of the model.
Recall the equation is something of the form y = x1*m1 + x2*m2 + x3*m3... + b
(only one coefficient for this model as it is very small data set)

### **3. Test Cases (Predictions)**

#### **Test 1**

In [6]:
model.predict([[5000]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

I do receive this warning after running the prediction. I believe this is because of what the professor mentioned in lecture on 9/9/2025. He mentioned how we are disregarding naming conventions as of now, but in the future we will use names such as X.test and X.values instead of simply using just X in the model training and predicting.

### **4. Saving Model (pickle)**

In [7]:
import pickle

In [8]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [9]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

Using pickle module we can create memory that holds the model. Pickle is the built in standard library in Python for this. It works, but can be slow for large data sets.

In [10]:
mp.predict([[5000]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Again the same error! You will see this a lot in my first few exercises, but the values from the predictions seem accurate enough to claim that I am doing things correctly.

### **5. Saving Model (joblib)**

In [11]:
import joblib

In [12]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [13]:
mj = joblib.load('model_joblib')

Joblib is an external module outside of the standard Python libraries that essentially does the same thing as pickle but in simple syntax. Joblib also excels better than pickle for larger data sets, I believe most times we will use this as a method of saving the model.

In [14]:
mj.predict([[5000]])

c:\Users\Micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [15]:
mj.coef_

array([135.78767123])

In [16]:
mj.intercept_

180616.43835616432

### **6. Conclusion**
Faily simple so far. This first model was very small and simple, most of the practice in this exercise involved the methods of saving the model in various ways.